
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Edu Pontes
 */
public class MarcaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form MarcaConsulta
     */
    public MarcaConsulta(String nome, String telefone) {
        initComponents();
        caixaNome.setText(nome);
        caixaTel.setText(telefone);
        try {
            ResultSet result = ConexaoBdClinica.stmt.executeQuery("SELECT nome FROM especialidade");
            while(result.next()){
                comboEspec.addItem(result.getString("nome"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(PrimeiroCadastroPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public MarcaConsulta() {
        initComponents();
        try {
            ResultSet result = ConexaoBdClinica.stmt.executeQuery("SELECT nome FROM especialidade");
            while(result.next()){
                comboEspec.addItem(result.getString("nome"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(PrimeiroCadastroPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboEspec = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboMedico = new javax.swing.JComboBox<>();
        botaoAtualizarMedico = new javax.swing.JButton();
        caixaTel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        caixaNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaConsultas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        caixaNome1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        caixaTel1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        caixaTel2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Marcar Consulta");

        jLabel3.setText("Especialidade*");

        comboEspec.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEspecItemStateChanged(evt);
            }
        });
        comboEspec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEspecActionPerformed(evt);
            }
        });

        jLabel5.setText("Médico de Preferência");

        comboMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMedicoMouseClicked(evt);
            }
        });
        comboMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMedicoActionPerformed(evt);
            }
        });

        botaoAtualizarMedico.setText("Atualizar Medicos");
        botaoAtualizarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarMedicoActionPerformed(evt);
            }
        });

        caixaTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTelActionPerformed(evt);
            }
        });

        jLabel2.setText("Telefone*");

        jLabel4.setText("Nome*");

        tabelaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaConsultas);

        jButton1.setText("Buscar Consultas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("HoraInicio");

        jLabel7.setText("HoraFim");

        caixaTel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTel1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Data");

        caixaTel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTel2ActionPerformed(evt);
            }
        });

        jButton2.setText("Marcar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboEspec, 0, 274, Short.MAX_VALUE)
                    .addComponent(comboMedico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caixaNome)
                            .addComponent(caixaTel))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAtualizarMedico))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caixaTel2)
                    .addComponent(caixaNome1)
                    .addComponent(caixaTel1)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboEspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAtualizarMedico)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(98, 98, 98)
                .addComponent(jButton2)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboEspecItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEspecItemStateChanged

    }//GEN-LAST:event_comboEspecItemStateChanged

    private void comboEspecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEspecActionPerformed

    }//GEN-LAST:event_comboEspecActionPerformed

    private void comboMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMedicoMouseClicked

    }//GEN-LAST:event_comboMedicoMouseClicked

    private void comboMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMedicoActionPerformed

    }//GEN-LAST:event_comboMedicoActionPerformed

    private void botaoAtualizarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarMedicoActionPerformed
        try {
            String espec = comboEspec.getSelectedItem().toString();
            String query = "SELECT M.nome FROM medico M, exerce as EX, especialidade as ESP WHERE M.crm = EX.crm AND EX.codigoespec = ESP.codigo AND ESP.nome = '" + espec + "'";
            ResultSet result = ConexaoBdClinica.stmt.executeQuery(query);
            comboMedico.removeAllItems();
            comboMedico.addItem("Sem Preferência");
            while(result.next()){
                comboMedico.addItem(result.getString("nome"));
            }
            if(comboMedico.getItemCount() == 1){
                comboMedico.removeAllItems();
                comboMedico.addItem("Não há médicos disponíveis para a especialidade.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(PrimeiroCadastroPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoAtualizarMedicoActionPerformed

    private void caixaTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaTelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String espec = (String) comboEspec.getSelectedItem();
        String medico = (String) comboMedico.getSelectedItem();
        if(medico.equals("Não há médicos disponíveis para a especialidade.")){
            JOptionPane.showMessageDialog(rootPane, "Não há médicos para essa especialidade");
        }else{
            if(medico.equals("Sem Preferência")){
                String query = "select M.nome, C.dataconsulta, C.horainicio, C.horafim from medico M, consulta C, especialidade ESP, exerce EX where M.crm = C.crm AND EX.crm = M.crm AND ESP.codigo = EX.codigoespec AND ESP.nome = '" + espec + "'";
                try {
                    ResultSet result = ConexaoBdClinica.stmt.executeQuery(query);
                } catch (SQLException ex) {
                    Logger.getLogger(MarcaConsulta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            String query = "select M.nome, C.dataconsulta, C.horainicio, C.horafim from medico M, consulta C, especialidade ESP, exerce EX where M.crm = C.crm AND EX.crm = M.crm AND ESP.codigo = EX.codigoespec AND ESP.nome = '" + espec + "' AND M.nome = '" + medico + "'";
            try {
                ResultSet result = ConexaoBdClinica.stmt.executeQuery(query);
                for(int i = 0; result.next(); i++){
                    for(int j = 0; j < 4; j++){
                        
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(MarcaConsulta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void caixaTel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaTel1ActionPerformed

    private void caixaTel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaTel2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nome = caixaNome.getText();
        String tel = caixaTel.getText();
        try {
            ResultSet result = ConexaoBdClinica.stmt.executeQuery("SELECT codigop from paciente where nome = '" + nome + "' AND telefone = '" + tel + "'");
            result.next();
            int codigoPaciente = result.getInt("codigop");
            result = ConexaoBdClinica.stmt.executeQuery("SELECT codigo from especialidade where nome = '" + (String)comboEspec.getSelectedItem() + "'");
            result.next();
            int codigoEspecialidade = result.getInt("codigo");
        } catch (SQLException ex) {
            Logger.getLogger(MarcaConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarcaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarcaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarcaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarcaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarcaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizarMedico;
    private javax.swing.JTextField caixaNome;
    private javax.swing.JTextField caixaNome1;
    private javax.swing.JTextField caixaTel;
    private javax.swing.JTextField caixaTel1;
    private javax.swing.JTextField caixaTel2;
    private javax.swing.JComboBox<String> comboEspec;
    private javax.swing.JComboBox<String> comboMedico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelaConsultas;
    // End of variables declaration//GEN-END:variables
}
